Moving Feature Labels
SIMPLE-AstroDB/SIMPLE-web pull request #74
Opened 2022-01-18 22:06 UTC by Will-Cooper

Closes #72

2022-01-20 20:31 UTC, kelle commented
- I like how you offset the lines from the bands.
- i think there are still too many bands shown. They overlap too much. I vote for getting rid of water and H2. Lemme see if I can comment on the code directly.

2022-01-20 20:33 UTC, kelle requested changes
Remove CIA H2 label.

2022-01-20 20:33 UTC, kelle commented on simple_app/plots.py
> +    'h2': {'altname': ['cia h2'], 'label': r'H₂', 'type': 'band', 'wavelengths': [[1.5, 2.4]]},
```suggestion
```
this is too big of a feature so I vote to not display it.

2022-01-20 20:33 UTC, kelle commented on simple_app/plots.py
> +                   'T Dwarf Features': ['k', 'ch4', 'h2o', 'h2'],
```suggestion
    featuresall = {'L Dwarf Features': ['k', 'na', 'feh', 'tio', 'co', 'h2o'],
                   'T Dwarf Features': ['k', 'ch4', 'h2o'],
```

2022-01-25 20:44 UTC, dr-rodriguez approved these changes

2022-01-25 20:46 UTC, kelle approved these changes

2022-01-25 20:51 UTC, merged