Reclaim Setup
SIMPLE-AstroDB/SIMPLE-web pull request #90
Opened 2022-06-06 15:21 UTC by Will-Cooper

The details about the changes made to get reclaim working (Apache/ jelastic/ flask).

2022-06-06 16:30 UTC, Will-Cooper commented
That path stuff was a real nuisance but now at least the tests work/ the site runs locally/ the site runs on reclaim

2022-06-07 16:31 UTC, Will-Cooper commented
This repo `main` branch is out of sync, but the new `reclaim` branch isn't as I've made the same changes in both places. That was manually though so I'd prefer to merge, then do a git pull in reclaim, to be sure it's alright.

2022-06-14 20:01 UTC, kelle commented
I think of rootpath as my path to "root" ...the upper most directory. But it's used here to mean the path to the simple app code. Consider renaming this file to simple_path

2022-06-14 20:03 UTC, kelle requested changes
Excellent progress!!

2022-06-14 20:03 UTC, kelle commented on README.md
> +<your/path/to/root>
```suggestion
<your/path/to/simple>
```

2022-06-14 20:03 UTC, kelle commented on simple_app.wsgi
> +sys.path.insert(0, "rootpath")
```suggestion
sys.path.insert(0, "simple_path/simple_app")
sys.path.insert(0, "simple_path")
```

2022-06-14 20:03 UTC, kelle commented on simple_app/app_simple.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_path/simple_app')
```

2022-06-14 20:29 UTC, kelle commented
`simple_root` sounds good to me!

2022-06-15 07:54 UTC, Will-Cooper commented on simple_app/utils.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_root/simple_app')
```

2022-06-15 07:55 UTC, Will-Cooper commented on simple_app/utils.py
> +    _args.add_argument('-f', '--file', default='rootpath/SIMPLE.db',
```suggestion
    _args.add_argument('-f', '--file', default='simple_root/SIMPLE.db',
```

2022-06-15 07:55 UTC, Will-Cooper commented on simple_app/utils.py
> +        with open('rootpath/simple_app/simple_callbacks.js', 'r') as fcall:
```suggestion
        with open('simple_root/simple_app/simple_callbacks.js', 'r') as fcall:
```

2022-06-15 07:56 UTC, Will-Cooper commented on simple_app/tests/test_utils.py
> +    copy('rootpath/SIMPLE.db', db_name)
```suggestion
    copy('simple_root/SIMPLE.db', db_name)
```

2022-06-15 07:56 UTC, Will-Cooper commented on simple_app/tests/test_utils.py
> +db_name = 'rootpath/temp.db'
```suggestion
db_name = 'simple_root/temp.db'
```

2022-06-15 07:57 UTC, Will-Cooper commented on simple_app/tests/test_utils.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_root/simple_app')
```

2022-06-15 07:57 UTC, Will-Cooper commented on simple_app/tests/test_plots.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_root/simple_app')
```

2022-06-15 07:58 UTC, Will-Cooper commented on simple_app/plots.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_root/simple_app')
```

2022-06-15 07:59 UTC, Will-Cooper commented on simple_app/app_simple.py
> +sys.path.append('rootpath/simple_app')
```suggestion
sys.path.append('simple_root/simple_app')
```

2022-06-15 08:32 UTC, Will-Cooper commented on README.md
> +Finally, in the `rootpath` symlink, swap
```suggestion
Finally, in the `simple_root` symlink, swap
```

2022-06-15 08:33 UTC, Will-Cooper commented on simple_app.wsgi
> +sys.path.insert(0, "rootpath")
```suggestion
sys.path.insert(0, "simple_root/simple_app")
sys.path.insert(0, "simple_root")
```

2022-06-21 19:30 UTC, dr-rodriguez approved these changes

2022-06-21 19:30 UTC, kelle approved these changes
This looks great!  Thanks for renaming the "root" directory. Reads much more clearly to me now.

2022-06-22 06:11 UTC, merged